"""Declared liquid single-name universe for event-volatility discovery."""

UNIVERSE: dict[str, str] = {
    "AAPL": "technology", "MSFT": "technology", "NVDA": "technology",
    "AVGO": "technology", "AMD": "technology", "INTC": "technology",
    "MU": "technology", "QCOM": "technology", "MRVL": "technology",
    "ORCL": "technology", "CRM": "technology", "ADBE": "technology",
    "IBM": "technology", "CSCO": "technology", "DELL": "technology",
    "HPE": "technology", "SNOW": "technology", "PLTR": "technology",
    "CRWD": "technology", "PANW": "technology", "ZS": "technology",
    "NOW": "technology", "DDOG": "technology", "NET": "technology",
    "GOOGL": "communication", "META": "communication",
    "NFLX": "communication", "DIS": "communication",
    "AMZN": "consumer_discretionary", "TSLA": "consumer_discretionary",
    "HD": "consumer_discretionary", "LOW": "consumer_discretionary",
    "MCD": "consumer_discretionary", "SBUX": "consumer_discretionary",
    "NKE": "consumer_discretionary", "LULU": "consumer_discretionary",
    "BKNG": "consumer_discretionary", "ABNB": "consumer_discretionary",
    "UBER": "consumer_discretionary", "COST": "consumer_staples",
    "WMT": "consumer_staples", "PG": "consumer_staples",
    "JPM": "financials", "BAC": "financials", "GS": "financials",
    "MS": "financials", "V": "financials", "MA": "financials",
    "PYPL": "financials", "COIN": "financials", "HOOD": "financials",
    "UNH": "healthcare", "LLY": "healthcare", "JNJ": "healthcare",
    "MRK": "healthcare", "PFE": "healthcare", "ABBV": "healthcare",
    "CAT": "industrials", "BA": "industrials", "GE": "industrials",
    "RTX": "industrials", "FDX": "industrials", "XOM": "energy",
    "CVX": "energy",
}
